#
# General rules
#

# MD012/no-multiple-blanks - Multiple consecutive blank lines
MD012:
  # Consecutive blank lines
  maximum: 3

# MD033/no-inline-html - Not part of our style guideline
MD033: false

#
# Rules conflicting with ascii text.
#

# MD034/no-bare-urls - Bare URL used
MD034: false

# MD037/no-space-in-emphasis - used as second level list
MD037: false

# MD041/first-line-heading/first-line-h1 - chapters are on level h2
MD041: false

# MD049/emphasis-style - asciidoc uses different styles
MD049: false

#
# Rules that may be applied when sticking to markdown code blocks.
#

# MD004/ul-style
MD004: false

# MD022/blanks-around-headings/blanks-around-headers
MD022: false

# MD023/heading-start-left/header-start-left
MD023: false

# MD026/no-trailing-punctuation
MD026: false

#
# Rules that are unclear whether they may be applied - may depend also on
# markdown code blocks.
#

# MD003/heading-style/header-style
MD003: false

# MD024/no-duplicate-heading
MD024: false

# MD027/no-multiple-space-blockquote
MD027: false

# MD052/reference-links-images
MD052: false
