[[general-guidelines]]
= General guidelines

The titles are marked with the corresponding labels: {MUST},
{SHOULD}, {MAY}.


[#100]
== icon:question-circle[1x] {SHOULD} follow API first principle

You should follow the <<api-first, API First Principle>>, more specifically:

* You should define APIs first, before coding its implementation, <<101, using
  OpenAPI as specification language>>
* You should call for early review feedback from peers and client developers,.


[#101]
== icon:question-circle[1x] {MUST} provide API specification using OpenAPI

We use the http://swagger.io/specification/[OpenAPI specification] as standard
to define API specification files. API designers are required to provide the API
specification using a single *self-contained YAML* file to improve readability.
We encourage to use *OpenAPI 3.0* version.

The API specification files should be subject to version control using a source
code management system - best together with the implementing sources.

You <<192, must / should publish>> the component <<219, external / internal>>
API specification with the deployment of the implementing service.

*Hint:* A good way to explore *OpenAPI 3.0/2.0* is to navigate through the
https://openapi-map.apihandyman.io/[OpenAPI specification mind map] and use
our https://plugins.jetbrains.com/search?search=swagger+Monte[Swagger Plugin
for IntelliJ IDEA] to create your first API. To explore and validate/evaluate
existing APIs the https://editor.swagger.io/[Swagger Editor] may be a good starting point.

[#102]
== icon:question-circle[1x] {SHOULD} provide API user manual

In addition to the API Specification, it is good practice to provide an API
user manual to improve client developer experience, especially of engineers
that are less experienced in using this API. A helpful API user manual
typically describes the following API aspects:

* API scope, purpose, and use cases
* concrete examples of API usage
* edge cases, error situation details, and repair hints
* architecture context and major dependencies - including figures and
sequence flows

The user manual must be published online, e.g. via our documentation hosting
platform service, GHE pages, or specific team web servers. Please do not forget
to include a link to the API user manual into the API specification using the
`#/externalDocs/url` property.


[#103]
== icon:question-circle[1x] {MUST} write APIs using U.S. English


[#234]
== icon:question-circle[1x] {MUST} only use durable and immutable remote references

Normally, API specification files must be *self-contained*, i.e. files
should not contain references to local or remote content, e.g. `../fragment.yaml#/element` or
`$ref: 'https://github.com/zalando/zally/blob/master/server/src/main/resources/api/zally-api.yaml#/schemas/LintingRequest'`.
The reason is, that the content referred to is _in general_ *not durable* and
*not immutable*. As a consequence, the semantic of an API may change in
unexpected ways. (For example, the second link is already outdated due to code restructuring.)
