name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build_docs:    
    name: Build documentation
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          make check-rules > check-rule-ids.log
          make all
      - name: Deploy to GitHub Pages
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
